### ISSUE TITLE
Snippet 0x09

### ISSUE THREAD

**Issue by ZaneH** [AlexAltea/blog#1]
I just worked [this](https://github.com/AlexAltea/blog/blob/master/posts/2016-10-12-xchg-rax-rax-solutions.md#snippet-0x09) one out, and I _think_ it's actually calculating `$rax / 8` and rounding to the closest integer.

**Comment by AlexAltea** [comment]
Right, that makes sense. Thanks! Just updated the solutions and added a couple of new ones.
