### ISSUE TITLE
Snippet 0x3B - "Random" Number Generator

### ISSUE THREAD

**Issue by DamianFekete** [AlexAltea/blog#6]
For [`Snippet 0x3B`](https://alexaltea.github.io/blog/posts/2016-10-12-xchg-rax-rax-solutions/) check https://skanthak.homepage.t-online.de/download/NOMSVCRT.H (modified sample here)

```c
__inline	// linear feedback shift register (Galois form)
unsigned long	cntr32(void)
{
	// primitive polynomials for maximum period length 2**32-1,
	//  grouped by number of coefficients:
...
	// 0x00400007, 0xC0000401 = x**32 + x**22 + x**2  + x**1 + x**0
...       
	// 0x04C11DB7, 0xDB710641 (CRC-32 IEEE)
...
	__asm	// returns result in eax
	{
		mov	eax, lfsr		; eax = lfsr
		cdq				; edx = (lfsr < 0) ? -1 : 0
		add	eax, eax		; eax = lfsr << 1
		and	edx, 0DB710641h		; edx = (lfsr < 0) ? polynomial : 0
						;     = polynomial'
		xor	eax, edx		; eax = lfsr' ^ polynomial'
						;     = lfsr"
		mov	lfsr, eax
	}
}
```

https://skanthak.homepage.t-online.de/nomsvcrt.html
> "Random" Number Generators
> The generators provided by the functions cntr32() ... are linear feedback shift registers alias Galois counters with period lengths of 2^32−1 and 264−1 respectively, ...

**Comment by AlexAltea** [comment]
Thank you for this insight. Makes sense that such a pattern appears in pseudo-random number generators. I've added an extra paragraph to solution 0x3B and credited you as well. Let me know if you want to update the URL of your name. :-)
